### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by adelgadox** [webponize/webponize#15]
Thanks for this app! It's amazing!

I have trouble to download it from your website: https://webponize.github.io/

The download button has a bad URL :  https://1000ch.github.io/webponize/webponize.tar.gz

I thinks the correct path is https://github.com/1000ch/WebPonize

Greetings!

**Comment by 1000ch** [comment]
https://github.com/webponize/webponize/issues/20#issuecomment-354647874 until https://webponize.org published.
