### ISSUE TITLE
Webponize Download

### ISSUE THREAD

**Issue by roppem9** [webponize/webponize#19]
When I go to "Download webponize.tar.gz", the link appears to be broken (bit.ly/webponize is the link that I'm being directed to). I keep getting a "404, File Not Found" message from git hub.

**Comment by aangelinsf** [comment]
I can confirm I'm seeing the same thing.

**Comment by lucasalvini** [comment]
Yes, it's still not working.

**Comment by 1000ch** [comment]
Would you use https://github.com/1000ch/WebPonize/raw/master/webponize.tar.gz to download temporary? I'm fixing whole of repo. 🙏

**Comment by 1000ch** [comment]
https://github.com/webponize/webponize/issues/20#issuecomment-354647874
