### ISSUE TITLE
Download link is broken...?

### ISSUE THREAD

**Issue by nicolasmiari-unext** [webponize/webponize#20]

**Comment by jlarmstrongiv** [comment]
> Would you use https://github.com/1000ch/WebPonize/raw/master/webponize.tar.gz to download temporary? I'm fixing whole of repo. 🙏
 👍 1  
—1000ch commented on Jan 24

**Comment by 1000ch** [comment]
Please download from [releases](https://github.com/webponize/webponize/releases) 🙏
