### ISSUE TITLE
Abandoned? Seems broken

### ISSUE THREAD

**Issue by JayHoltslander** [webponize/webponize#24]
Creates badly distorted images.

Mac OS X 10.13.6

**Comment by wottpal** [comment]
Was so happy to discover this easy tool, but this is very disappointing :(

**Comment by CougarNordic** [comment]
Same here. Mac 10.15.2, program takes the image and completely mangles it. I wished this worked, it's a lot easier than Google's program.

**Comment by idleberg** [comment]
Same here. To give an example, here are screenshots of both, input and output, images

**Before (PNG):**

![Screenshot 2020-07-06 at 12 54 35](https://user-images.githubusercontent.com/1504938/86586269-ee6f8e80-bf87-11ea-9449-79c4b17137fc.png)

**After (Webp):**

![Screenshot 2020-07-06 at 12 54 23](https://user-images.githubusercontent.com/1504938/86586321-fe876e00-bf87-11ea-9732-792c17e2c3f5.png)

**Comment by JayHoltslander** [comment]
Hey everyone. Just use [Squoosh App](https://squoosh.app/). It’s a progressive web app so you can install to Desktop via Chrome.

**Comment by idleberg** [comment]
> Hey everyone. Just use [Squoosh App](https://squoosh.app/). It’s a progressive web app so you can install to Desktop via Chrome.

It's hardly the same. For example, there is no batch mode.

**Comment by 1000ch** [comment]
Now it's difficult to build this app with the newest codebase because of the Apple Developer's codesign problem (slightly hard to solve). I'm willing to maintain this app, so please wait for a while.

**Comment by 1000ch** [comment]
You can install the newest version of WebPonize via [App Store](https://apps.apple.com/us/app/id1526039365?mt=12).

**Comment by JayHoltslander** [comment]
Nice to see the project is still alive. Batch conversion via GUI is a very nice feature to have here. Unfortunately I still get badly distorted images half of the time. Is it using cwebp?

**Comment by 1000ch** [comment]
@JayHoltslander 
WebPonize uses `libwebp` bundled with [Swift-WebP](https://github.com/ainame/Swift-WebP) to convert images. I want to figure out what is the problem of that, but It is difficult to debug the internal process of `libwebp`. Can you share those images? it might be solved by fixing the bitmap data by tools like [ImageOptim](https://imageoptim.com/) or some other encoders.

**Comment by JayHoltslander** [comment]
Here is [a zip file of the batch of images](https://cdn.holtslander.ca/Archive.zip) that I tested with.

**Comment by 1000ch** [comment]
@JayHoltslander 
Thank you, downloaded and confirm that they will be broken by conversion. Also, I could convert those images successfully after decoding those JPEGs using ImageOptim as a workaround.

Anyway, this should be solved by `libwebp` 🤔

**Comment by JayHoltslander** [comment]
I'm not clear on the method you used with my test images but I ran them through ImageOptim 1.8.8 and then through Webponize and still had the same result with broken images as before when I skipped ImageOptim.

**Comment by 1000ch** [comment]
I tried to encode them using ImageOptim 1.8.8 with "lossy minification" and "85% JPEG quality". Of course, it was a workaround.

**Comment by 1000ch** [comment]
[The `v2.6.0` version was published on the App Store](https://apps.apple.com/us/app/id1526039365?mt=12) that includes [the newest `libwebp`](https://github.com/webponize/webponize/commit/75214408961ec774ef16a2845bf4ba9d5b32c56d). Would you please try it? I want to know the situation was improved or not.
