### ISSUE TITLE
App was pulled down from App Store?

### ISSUE THREAD

**Issue by Ranoiaetep** [webponize/webponize#33]
Seems like the app was pulled down from the store, or at least in the United State store.

For some reason Carthage wasn't quite working on my machine either, and took me awhile to rebuild/configure dependence.

Hope the app will be back to the store, and best wishes @1000ch !

**Comment by 1000ch** [comment]
@Ranoiaetep I reactivated my Apple Developer account to resurrect [WebPonize](https://apps.apple.com/us/app/id1526039365?mt=12), thank you for your report!

**Comment by theo-69** [comment]
its gone again

**Comment by subfighter3** [comment]
Any chance is going to resurrect again @1000ch ?
