### ISSUE TITLE
My image does not work

### ISSUE THREAD

**Issue by enjikaka** [webponize/webponize#8]
When I try to WebPonize this image -> https://www.dropbox.com/s/tb9cs6nxk9ifzca/plypp-piano.png?dl=0

It fails.

**Comment by 1000ch** [comment]
Sorry. But it seems to be resolved with the newest version.
Please try again with v1.2.1?

**Comment by 1000ch** [comment]
Fixed on [`v2.0.0`](https://github.com/webponize/webponize/releases/tag/v2.0.0).
